### ISSUE TITLE
Hide the mask

### ISSUE THREAD

**Issue by eduardodallmannsysmap** [eduardoborges/use-mask-input#61] opened 2023-10-10 17:03 UTC
Is there any way to hide the mask and only show it when typing is in the right place?

Example with cleave.js (that's what I want):
![cleave](https://github.com/eduardoborges/use-mask-input/assets/125034095/d746c1c3-857f-4746-ad15-517e6623d7fc)

With use-mask-input:
![rut](https://github.com/eduardoborges/use-mask-input/assets/125034095/a8a18712-a72d-4af7-b5b2-f28e0870d12c)

I want to thank you for the lib. It's perfect.

**Comment by eduardodallmannsysmap** [comment] 2023-10-10 17:32
I see #51 issue, but doesn't work. What's wrong?

https://codesandbox.io/s/modern-breeze-3y6tw7

**Comment by eduardoborges** [comment] 2023-10-17 17:32
Can you provide more artifacts from your problem? Which mask are u using? Can u show me the code? :D

**Comment by Mateusvaz89** [comment] 2023-11-06 23:15
I want to hide the mask too. jitMasking is not working..

**Comment by eduardoborges** [comment] 2023-11-06 23:28
@Mateusvaz89 whay you mean with "hide the mask"? You can pass a mask with white spaces if you what an "invisible" mask.

**Comment by eduardodallmann** [comment] 2023-11-07 18:55
The problem is in this line

https://github.com/eduardoborges/use-mask-input/blob/b4aef47927c2e0ecb2f2d1c926edc4700cb887c7/src/utils/getMaskOptions.ts#L6

It is fixed jitMasking to false

**Comment by eduardoborges** [comment] 2023-11-07 23:42
@eduardodallmann uuhh nice catch ⚾️

**Comment by eduardoborges** [comment] 2023-11-13 12:26
@Mateusvaz89 i fixed in latest version, can u try it?

**Closed as completed** 2023-11-27 19:26 UTC
